### ISSUE TITLE
Remnants of a Git Merge?

### ISSUE THREAD

**Issue by KAfable** [BlackJar72/DoomlikeDungeons#11]
I'm not too familiar with Git overall but I think the mesa.cfg in themes has remnants of a Git Merge?

```
<<<<<<< HEAD
liquid =  minecraft:water, minecraft:lava, minecraft:air, minecraft:air, minecraft:sand
=======
liquid =  minecraft:water, minecraft:water, minecraft:lava, minecraft:air, minecraft:air, minecraft:sand
liquid =  minecraft:water, minecraft:lava, minecraft:air, minecraft:sand, minecraft:sand
>>>>>>> origin/master
```

**Comment by KAfable** [comment]
Also, this cfg file seems to have multiple ceilings, floors, walls, and etc. for its entries - does this add more complexity or choices for generating the dungeon? Or was this also unintentional?

**Comment by BlackJar72** [comment]
What game version that from -- yeah, that is why I stopped using git when moving features between game versions, but I can't believe some of it has persisted this long.

As for multiples -- these are lists of blocks, so more to choose from.  As for any duplications, it uses a very simple system where each entry is one chance, so the same thing in more than one entry is how things are given different weights.

**Comment by BlackJar72** [comment]
I've fixed this in the latest version.

Actually, it may be the final version.  I've said that before, and later came back, but my life is changing now, I'll have much less freetime in the very near future.

I hope everything is in good shape now.
