### ISSUE TITLE
Anyway to specify loot per dungeon?

### ISSUE THREAD

**Issue by KAfable** [BlackJar72/DoomlikeDungeons#18]
Would it be possible to specify a specific dungeon theme to point to a different chests.cfg file instead of the default one? We want to have varied loot per dungeon, and dungeons in space dimensions will be more difficult/harder mobs than the overworld dungeon and wanted to have a separate loot table for them.

**Comment by BlackJar72** [comment]
Well, it's not possible right now -- but maybe in an update.  I'd toyed with the idea before but was worried about making the system too complex.  I may go ahead and do this soon.

**Comment by KAfable** [comment]
Awesome, it would be appreciated if you can, right now the closest you can get is really janky approximations by populating the common Mobs category with tough mobs like Witches, ut still the loot being equivalent throughout all dungeons is worrying.

**Comment by Saereth** [comment]
just wanted to chime in as well and say this would open a ton of options up to packmakers, would be really appreciated if its something you're up for.

**Comment by BlackJar72** [comment]
It may be over the weekend, but hopefully soon.  The code involved is old meaning (1) its deep in the mod, and (2) it's not as well designed as newer parts.  But I should be able to rework it.

**Comment by BlackJar72** [comment]
OK, you should now be able to add special loot using special chest files in the SpecialChests folder.
