### ISSUE TITLE
1.12.2 Spawner [Error] after lycanite mob entity added to theme config (Displayed when viewed with Walia)

### ISSUE THREAD

**Issue by Needmoremods** [BlackJar72/DoomlikeDungeons#26]
As title describes. 

1.12.2 Spawner ERROR after lycanite mob entity added to theme config (Error is displayed next to Spawner name when viewed with Walia). 

I added lycanite mob entity names to separate themes in the themes folder for config but got this error in game. Format for the entity used is as follows: entity.mobtype.mobname

Edit* I also cannot seem to find lycanite themed dungeons spawning, unsure if this is due to rarity or not as I could not find anything related in the config.

**Comment by BlackJar72** [comment]
Correct format is modid:mobname, examples:

minecraft:skeleton
dungeonmobs:dmmanticore
thaumcraft:wisp

Try turning on the option to export lists in the main DLDungeonsJBG.cfg, then look at lists/entities.txt -- you should find what you need there.
