### ISSUE TITLE
Game Crash on startup (1.7.10)

### ISSUE THREAD

**Issue by Zxaleb27** [BlackJar72/DoomlikeDungeons#32]
[crash-2021-08-15_22.41.55-client.txt](https://github.com/BlackJar72/DoomlikeDungeons/files/6989456/crash-2021-08-15_22.41.55-client.txt)
The game crashed whilst initializing game
Error: java.lang.IllegalArgumentException: No enum constant jaredbgreat.dldungeons.nbt.NBTType.JSON
Exit Code: -1
No other mods present.

**Comment by BlackJar72** [comment]
I'll have to look at this in a few days -- which will involve setting up a new dev environment for 1.7.10.  I'm not sure the NBT system ever was working in that version, and incomplete code for it may have been left in by accident and included with another bug fix by mistake.

**Comment by BlackJar72** [comment]
I don't know if I can do this or not, since the code for the MC1.7.10 versions has somehow been deleted -- I certainly didn't do it, but somehow the 1.7.10 branch has disappeared.

**Comment by BlackJar72** [comment]
Never mind, what you have is not a bug, its just that the 1.7.10 versions didn't support JSON, that was added later -- I think it depends on something in the vanilla code that isn't even in 1.7.x.  Sorry, you just will have to remove the JSON tag.
