### ISSUE TITLE
Cascading worldgen lag on version 1.14.7-MC1.12.2

### ISSUE THREAD

**Issue by Zalnor** [BlackJar72/DoomlikeDungeons#34]
The version 1.14.7-MC1.12.2 of DoomlikeDungeons mod linked bellow causes cascading worldgen lag, by itself it wouldn't be that bad but in any sizeable modpack it adds on quite a bit of cascading worldgen lag. I have also included a link explaing exactly what that is and how to go about fixing it. Example setting and offset or flags when structures are spawned partially in a chunk and when adjesent chunks load it reads it and finishes generating the structure.

https://www.reddit.com/r/feedthebeast/comments/5x0twz/investigating_extreme_worldgen_lag/

https://www.curseforge.com/minecraft/mc-mods/project-74246/files/3363932

**Comment by BlackJar72** [comment]
It looks like my generator needed offsets of +16 instead of the usual +8.

If this holds, it may make an update to newer games versions possible.

**Comment by BlackJar72** [comment]
Please see if 1.14.8 is better.

**Comment by Zalnor** [comment]
I have done some tests with the new version, and I do not see anymore cascading worldgen lag from 1.14.8 even with 300+ mods. Thanks for the quick response and fix!

**Comment by BlackJar72** [comment]
You were lucky -- I'd tried before and given up.  I almost flagged this as "wontfix," but I decided to go ahead and check one last thing, and there it was, the problem that had eluded me before.
