### ISSUE TITLE
Missing mcmod.info

### ISSUE THREAD

**Issue by The-Fireplace** [BlackJar72/DoomlikeDungeons#4]
![2017-06-04_00 30 22](https://cloud.githubusercontent.com/assets/5914284/26759190/07a7306e-48bd-11e7-9ae4-6519108dcafe.png)
Doomlike Dungeons 1.9.0, Minecraft 1.11.2

**Comment by BlackJar72** [comment]
https://github.com/BlackJar72/DoomlikeDungeons/blob/MC1.11.2/resources/mcmod.info

It's been there a long time -- it doesn't seem to work with some versions, but it's there.

**Comment by The-Fireplace** [comment]
Try replacing "authors" with "authorList"
That's the only difference I see between that and a working mcmod.info.

**Comment by BlackJar72** [comment]
OK, I tried that.  We'll see if it works in the next version.  I'm already working on new version that will allow multi-level dungeons (1.10.0) so it will be in that as far as an official release.

(Sneaky Forge team, changing these formats one me....)
