### ISSUE TITLE
log

### ISSUE THREAD

**Issue by ArtElleys** [BlackJar72/DoomlikeDungeons#5]
11:03:02	game		[09:03:02] [main/INFO]: [STDOUT]: [DLDUNGEONS] Loading chest loot file (chests.cfg)
11:03:02	game		[09:03:02] [main/INFO]: [STDERR]: [DLDUNGEONS] ERROR! Item read as "minecraft:golden_apple(1)" was was not in registry (returned null).
11:03:02	game		Jul 02, 2017 9:03:02 AM jaredbgreat.dldungeons.debug.Logging LogError
11:03:02	game		SEVERE: [DLDUNGEONS] ERROR! Item read as "minecraft:golden_apple(1)" was was not in registry (returned null).
11:03:02	game		[09:03:02] [main/INFO]: [STDERR]: [DLDUNGEONS] ERROR! Item read as "minecraft:golden_apple(1)" was was not in registry (returned null).
11:03:02	game		Jul 02, 2017 9:03:02 AM jaredbgreat.dldungeons.debug.Logging LogError
11:03:02	game		SEVERE: [DLDUNGEONS] ERROR! Item read as "minecraft:golden_apple(1)" was was not in registry (returned null).
11:03:02	game		[09:03:02] [main/INFO]: [STDERR]: [DLDUNGEONS] ERROR! Item read as "minecraft:golden_apple(1)" was was not in registry (returned null).
11:03:02	game		Jul 02, 2017 9:03:02 AM jaredbgreat.dldungeons.debug.Logging LogError
11:03:02	game		SEVERE: [DLDUNGEONS] ERROR! Item read as "minecraft:golden_apple(1)" was was not in registry (returned null).
11:03:02	game		[09:03:02] [main/INFO]: [STDERR]: [DLDUNGEONS] ERROR! Item read as "minecraft:golden_apple(1)" was was not in registry (returned null).
11:03:02	game		Jul 02, 2017 9:03:02 AM jaredbgreat.dldungeons.debug.Logging LogError
11:03:02	game		SEVERE: [DLDUNGEONS] ERROR! Item read as "minecraft:golden_apple(1)" was was not in registry (returned null).
11:03:02	game		[09:03:02] [main/INFO]: [STDERR]: [DLDUNGEONS] ERROR! Item read as "minecraft:skull(1)" was was not in registry (returned null).
11:03:02	game		Jul 02, 2017 9:03:02 AM jaredbgreat.dldungeons.debug.Logging LogError
11:03:02	game		SEVERE: [DLDUNGEONS] ERROR! Item read as "minecraft:skull(1)" was was not in registry (returned null).
11:03:02	game		[09:03:02] [main/INFO]: [STDERR]: [DLDUNGEONS] ERROR! Item read as "minecraft:skull(1)" was was not in registry (returned null).
11:03:02	game		Jul 02, 2017 9:03:02 AM jaredbgreat.dldungeons.debug.Logging LogError
11:03:02	game		SEVERE: [DLDUNGEONS] ERROR! Item read as "minecraft:skull(1)" was was not in registry (returned null).

**Comment by BlackJar72** [comment]
OK, this bug seems to have been introduced as a sloppy dumb mistake in the update for 1.11.  It's now fixed for 1.11.2 and 1.12.
