### ISSUE TITLE
When Making a Custom Theme, Modded Blocks are Air Instead.

### ISSUE THREAD

**Issue by TeetoKaziim** [BlackJar72/DoomlikeDungeons#6]
DoomlikeDungeons-1.10.0-MC1.12.2
Minecraft 1.12.2
Forge 14.23.1.2560
Quark-r1.4-120 (The mod that the blocks I'm trying to use are from)

I'm customizing all of the dungeon profiles in my pack to pretty them up a bit, but am running into a problem: It seems that the dungeon generator isn't placing any blocks except for those from vanilla minecraft. I've observed this effect on wall, floor, fluid and cieling blocks for sure.

The vanilla blocks I chose are showing up, pools of solid magma, floors of soul sand, walls of red nether brick, so it's definitely using the config.

Attached is the nether.cfg I'm using to set the theme.
https://pastebin.com/raw/y0c4gRJ7

Thanks for your time and consideration.

**Comment by BlackJar72** [comment]
I'll look into this.  I actually haven't test this feature in newer versions since my modpacks so far have been for 1.6.4 and 1.7.10 (to use the MineFantasy mod).  One question -- do you find any areas where a wall or floor is just missing, like the room just come right up to stone without any wall.  That could be important in telling if it isn't selecting them, or is placing them incorrectly (using an invalid block in their place)?

**Comment by TeetoKaziim** [comment]
So I whipped up an imgur album, because I think I'm gonna fail to clearly describe what i'm seeing with words alone, and don't want to miscommunicate (I'm not sure I fully understand the distinction in how it would look between the 2 cases you describe):

https://imgur.com/a/oWapN

The dungeons seen here were generated using a new custom theme I whipped up specifically for testing:

https://pastebin.com/raw/Qn0BXNKq

Basically, i think it's trying to place "something", and is placing air instead? But my understanding of minecraft's worldgen or any kind of code is nil, so you'd probably be better able to tell.

Also, I've double checked, in an instance with just the latest versions of:
Forge
Doomlike Dungeons
Jei
Hwyla
Quark
Autoreglib (A dependency for Quark)

And it is still happening, so that mostly rules out cross-mod interference (unless it's one of those 4). In my main pack, I have about 90 mods, so I didn't want to be sending you on a wild goose chase that was actually being caused by some other mod.

I hope this information proves useful, and, the best to ya. Honestly, in the meantime, I can make do, in 1.12, concrete and glazed terracotta really widen out the options a lot more than they were in earlier versions, even without resorting to mods blocks. And the gameplay parts, monster spawners and chest treasure, appear to be working juuuuuuuuust fine :D.

**Comment by BlackJar72** [comment]
OK, that's what I needed to know -- its clearly trying place the modded blocks, but its placing a block that doesn't exist in the game instead (so you end up with no block at all).  This probably means one of several things: either Doomlike Dungeons is failing to get blocks correctly (my problem) or Quark is not registering the block at the correct phase.  So, I need to see what it does with this and with other mods.

**Comment by BlackJar72** [comment]
I've tested it out using both Quark and Rustic (as a kind of control), and apparently it does not get the correct block objects (or block states) in 1.12.2 (and for how many versions) since it will not place blocks from either mod.  I'll look into why this is.

**Comment by BlackJar72** [comment]
Fixed it.  A bug fixed version has been uploaded and should be available as soon as Curse is done reviewing it.

**Comment by TeetoKaziim** [comment]
Seriously though, thankyou. The wild customisability in this mod has made it a real joy to fuss with in every pack I've made.

https://i.imgur.com/b0n7nhM.png
