### ISSUE TITLE
NBT Strting can't transcoding chinese or special symbols

### ISSUE THREAD

**Issue by HaoranWang2000** [BlackJar72/DoomlikeDungeons#9]
Hi,
I'm making my magic theme modpack(in chinese),and DLDungeons is one of the most inportant mod.Use NBT.cfg,I made a lot of custom item,like shrunken potion,blink bedge,waterwalking boots etc.
Then I tried to gave them name and lore,at first I did it like the example,but I realized the string between "" will be commented out.So I deleted all double quotation mark,then like lot of MC mod,input chinese characters and special symbols directly will became messy code.
Next I use some transcoding tools,to transcoding chinese characters into Unicode,for example,chhinese characters 药水(means potion) became \u836F\u6C34,and if there's no mistake,in game that code will become 药水 again like other MC mod.
But the code still are code,like \u836F\u6C34 became u836Fu6C34 in game.
I spend 3 days,changed config file's encoding mode,changed string's format,updated mod version from 1.9.4-MC1.7.10 to 1.10.2,then from 1.10.2 to today's latest 1.11.0,and I tried every idea I thought of,I can't find ANY way to input chinese characters!
Provided you could fix this or tell me how to input chinese and special symbols,that would be nice,thanks.
BTW,my forge version is 1.7.10-Forge10.13.4.1614.

**Comment by BlackJar72** [comment]
I thought Java would take care of it as long as someone could input the characters in their editor.  I assumed Java's build in use of unicode would allow all characters that fit in 16 bits.  I just took it for granted I was covered for non-Latin alphabets.

I've looked into it.  I'm sorry, I don't think I can fix this.  I'm not a professional program and have no formal training.  I'm just who learned a little Java and thought it would fun to have big dungeon in Minecraft.  I wish I could help, but I'm beat.  I tried to make it work, but I can't even get my tokenizer to parse escape characters in general correctly.  I wish I could help, but I don't think I can do anything about this.  Sorry.

**Comment by BlackJar72** [comment]
I did a test, and I found it had no trouble printing "药水" -- I have no idea what that says (I cut and pasted from a friends post on Facebook).  So, apparently it can print non-Latin characters, you just have to put them in literally, not as unicode.

**Comment by BlackJar72** [comment]
Sorry, it took so long.  If you want another way to input Chinese characters you can now use Unicode.

/u####

Where #### is the hexadecimal for the Unicode.  I hope this helps.
